version: "3.7"

services:
  oc-patient:
    container_name: oc-patient
    build: ./oc-patient
    restart: always
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "oc-patient", "3001"]
      interval: 30s
      timeout: 10s
    depends_on:
      - mongodb
      - rabbitmq
    links:
      - mongodb
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb:27017
      - RABBITMQ_URI=rabbitmq:5672

  oc-gateway:
    container_name: oc-gateway
    build: ./oc-gateway
    restart: always
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "oc-gateway", "3000"]
      interval: 30s
      timeout: 10s
    depends_on:
      oc-patient:
        condition: service_healthy
    links:
      - oc-patient
    environment:
      - OC_PATIENT_URI=oc-patient:3001

  mongodb:
    image: mongo:4.4
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - RABBITMQ_ERLANG_COOKIE=open-clinic