version: 3.7

services:
  patient:
    build: ./oc-patient
    restart: always
    container_name: oc-patient
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "localhost", "3001"]
      interval: 30s
      timeout: 10s
    networks:
      - backend
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/openclinic
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - "./oc-patient:/app"

  gateway:
    build: ./oc-gateway
    restart: always
    container_name: oc-gateway
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "localhost", "3000"]
      interval: 30s
      timeout: 10s
    networks:
      - backend
    depends_on:
      patient:
        condition: service_healthy
    environment:
      - NODE_ENV=development
    volumes:
      - "./oc-gateway:/app"

  mongodb:
    image: mongo:4.4
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - "mongo:/data/db"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - RABBITMQ_ERLANG_COOKIE=open-clinic
    networks:
      - backend

networks:
  backend:
